spring.application.name=Project2

#Database
spring.datasource.url = jdbc:postgresql://postgres:GxXshtNPDwBWlpuIGuNyQbkmgrSrYLsP@autorack.proxy.rlwy.net:43630/railway
spring.datasource.username = postgres
spring.datasource.password = GxXshtNPDwBWlpuIGuNyQbkmgrSrYLsP

#JPA
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=dunghoihanvequakhukhonglolangvetuonglaisongchohientai
jwt.expiration=86400000
jwt.refresh-expiration=604800000

#VNPay Sandbox
vnpay.tmn-code=LF36RNMN
vnpay.hash-secret=1T257SE7HBAPDABPNBQCSYV0YQEI8B3M
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/callback

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# Redis for rate limiting
spring.data.redis.host=redis.railway.internal
spring.data.redis.port=6379
spring.data.redis.password=oGeqfaiSpyDoPGGEOflKKumXyZKffdQQ
spring.data.redis.database=0
spring.data.redis.timeout=2s

